### PR TITLE
update documentation in context of new release v1.2.0 of Concordion.NET

### PR DESCRIPTION
**Pull request by ShaKaRee**

### CODE REVIEW

**Comment by ShaKaRee** [comment]
see individual commits within concordion-net project history:
https://github.com/concordion/concordion-net/commits/gh-pages

**Comment by ShaKaRee** [comment]
@nigelcharman would you review these please, and merge if you're happy with them

**Comment by nigelcharman** [comment]
I started making line comments on these commits, then changed over to making the comments on the individual commits. Mostly grammatical and spelling comments. thanks

**Comment by ShaKaRee** [comment]
@nigelcharman thank you for all your great comments.
I have updated the documentation and added some comments.
Could you merge, if you are happy with the changes?
I am keen to provide the information about the new release on the website soon.

**Comment by nigelcharman** [comment]
Great. I've merged it now, thanks.

**Pull request merged**
